# ~/.tmuxinator/test.yml

name: work
root: ~/workspace

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: hello

# Controls whether the tmux session should be attached to automatically. Defaults to true.
attach: true

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t test

windows:
  - ~/dotfiles:
      root: ~/
      layout: 0bef,181x52,0,0[181x44,0,0,21,181x7,0,45,22]
      panes:
        - vim -O ~/.vimrc ~/.zshrc
        - #empty
  - code:
      layout: 0bef,181x52,0,0[181x44,0,0,21,181x7,0,45,22]
      panes:
        - vim
        - #empty
  - hello:
      root: ~/
      layout: 5bb1,181x52,0,0,31
      panes:
        - archey -c
